[project]
name = "awrfo-simulator-service"
version = "0.0.1"
description = "Simulation service for AWRFO"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "awrfo-contracts",

    "redis[hiredis]>=7.1.0",
]

[tool.uv.sources]
awrfo-contracts = { workspace = true }

[tool.ruff]
line-length = 88
target-version = "py312"
