[project]
name = "awrfo-simulator-service"
version = "0.0.1"
description = "Simulation service for AWRFO"
authors = [{ name = 'Cafesuada', email = 'connghiencafe@protonmail.com' }]
maintainers = [{ name = 'Cafesuada', email = 'connghiencafe@protonmail.com' }]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "awrfo-python",
    "fastapi[standard]>=0.124.4",
    "pydantic>=2.12.5",
    "redis[hiredis]>=7.1.0",
    "python-dotenv>=1.2.1",
]

[tool.uv.sources]
awrfo-python = { workspace = true }

