syntax = "proto3";

package awrfo.contracts.events.task.v1;

import "buf/validate/validate.proto";
import "awrfo/contracts/envelopes/event_envelope/v1/event_envelope.proto";

message TaskAssignmentRejectedEvent {
  awrfo.contracts.envelopes.event_envelope.v1.EventEnvelope envelope = 1;

  optional string assignment_id = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];

  optional string task_id = 3 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];

  optional string robot_id = 4 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];

  optional uint64 ts_ms = 5 [
    (buf.validate.field).required = true
  ];

  optional string reason = 6 [
    (buf.validate.field).required = true
  ];
}
